language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
    - "ui/node_modules"
script: npm install && npm run tsc && npm test && cd ui && npm install && CI=false npm run-script build